// Generated by Garaga version 1.0.1

use garaga::definitions::{E12D, G2Point, u288, u384};

pub const N_PUBLIC_INPUTS: usize = 4;

pub const ALPHA_BETA_MILLER_LOOP_RESULT: E12D = E12D {
    w0: u288 {
        limb0: 0xfd1e484e252ab2d0f1d4a806,
        limb1: 0x825bd7c836582db4ceec2c2a,
        limb2: 0x18bde7d6e4a78e0f,
    },
    w1: u288 {
        limb0: 0xe443f61ec17d75cc529dbeab,
        limb1: 0xd311a18f3c48813810f0a4b2,
        limb2: 0x1857fc9c95dfa6e2,
    },
    w2: u288 {
        limb0: 0xb6e462b37bdbcac66347ec19,
        limb1: 0xe8629545b73bd047b5913684,
        limb2: 0x21d5405ea928037b,
    },
    w3: u288 {
        limb0: 0x9ca6cafdfe08816d5df027ff,
        limb1: 0x4a6ee142e72e0f8dc4cf29b5,
        limb2: 0x18d383b74a668d98,
    },
    w4: u288 {
        limb0: 0xb2cb38a2df4ac6fb24c886da,
        limb1: 0x81bc6e541a26719cd2cb9cb1,
        limb2: 0x20b0f804b95fe80e,
    },
    w5: u288 {
        limb0: 0xbaa65f8073a5c9c6c127405c,
        limb1: 0xf6a214da091e954e29e62711,
        limb2: 0x17ec1d0254ed5724,
    },
    w6: u288 {
        limb0: 0x5cd8ac9a4792b2bda4ba6af2,
        limb1: 0x7ec7348cf9de7efb19a3e1a7,
        limb2: 0x25c366bf2b403ca7,
    },
    w7: u288 {
        limb0: 0x5d872418f534d78682a5569c,
        limb1: 0x191fc6bfc1a4db787a66217,
        limb2: 0x2e6cbde09223125c,
    },
    w8: u288 {
        limb0: 0x2ff0a2ded46ddba47cf2059a,
        limb1: 0xb884378588fd5cd8b0a94ce2,
        limb2: 0x11c6abc64bd1e825,
    },
    w9: u288 {
        limb0: 0x260b72aefa879627a10d0093,
        limb1: 0x49240e35e4ddc7a63331fa9b,
        limb2: 0x126b07d4918bc3c1,
    },
    w10: u288 {
        limb0: 0xf6267f7a3fcac43e1bdf84e1,
        limb1: 0xd9505a43bcb9836fc8ad0604,
        limb2: 0xd5f0d3b31b9bf39,
    },
    w11: u288 {
        limb0: 0xe6314dd51c5e74083152420f,
        limb1: 0x81926cc18eb08ae2edaf3794,
        limb2: 0x226f94657ae01274,
    },
};

pub const GAMMA_G2: G2Point = G2Point {
    x0: u384 {
        limb0: 0xf75edadd46debd5cd992f6ed,
        limb1: 0x426a00665e5c4479674322d4,
        limb2: 0x1800deef121f1e76,
        limb3: 0x0,
    },
    x1: u384 {
        limb0: 0x35a9e71297e485b7aef312c2,
        limb1: 0x7260bfb731fb5d25f1aa4933,
        limb2: 0x198e9393920d483a,
        limb3: 0x0,
    },
    y0: u384 {
        limb0: 0xc43d37b4ce6cc0166fa7daa,
        limb1: 0x4aab71808dcb408fe3d1e769,
        limb2: 0x12c85ea5db8c6deb,
        limb3: 0x0,
    },
    y1: u384 {
        limb0: 0x70b38ef355acdadcd122975b,
        limb1: 0xec9e99ad690c3395bc4b3133,
        limb2: 0x90689d0585ff075,
        limb3: 0x0,
    },
};
