// Generated by Garaga version 1.0.1

//! # Starknet Verification Contract Tests
//!
//! This module contains comprehensive tests for the proof verification contract.
//! The tests use Starknet Foundry's testing features to verify proofs.
//!
//! ## Test Strategy
//! - Use real proof fixtures generated by the garaga CLI
//! - Test both positive (valid proof) and negative (invalid proof) cases

// To run the integration test, you need:
// 1. A valid proof.json file
// 2. Generate calldata: `garaga calldata --system groth16 --vk path/to/vk.json --proof proof.json --format snforge --output-path tests/`
// 3. Uncomment the test below

// use semacairo::groth16_verifier::{
//     IGroth16VerifierBN254DispatcherTrait, IGroth16VerifierBN254LibraryDispatcher,
// };
// use snforge_std::fs::{FileTrait, read_txt};
// use snforge_std::{DeclareResultTrait, declare};
// use starknet::ClassHash;

// fn declare_contract(name: ByteArray) -> ClassHash {
//     let class_hash = *declare(name).unwrap().contract_class().class_hash;
//     class_hash
// }

// #[test]
// #[fork(url: "https://rpc.starknet-testnet.lava.build:443", block_tag: latest)]
// fn test_verify_groth16_proof_bn254() {
//     let class_hash = declare_contract("Groth16VerifierBN254");
//     let dispatcher = IGroth16VerifierBN254LibraryDispatcher { class_hash };

//     let file = FileTrait::new("tests/proof_calldata.txt");
//     let calldata = read_txt(@file).span();

//     let result = dispatcher.verify_groth16_proof_bn254(calldata);

//     assert(result.is_ok(), 'Proof verification failed');
// }
